# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Development

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Development
      working-directory: ./test/
      run: |
        npm ci
        npm run build --if-present
    - name: git settings
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Check files
      working-directory: ./test/
      run: |
        cd htdocs
        ls
    - name: Commit files
      run: |
        git add .
        git commit -m "build" -a
        git push origin development
