# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: reviewdog

on:
  pull_request:
    types: [opened, synchronize]


defaults:
  run:
    working-directory: ./test

jobs:
  eslint:
    name: Check Eslint Error
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          eslint_flags: './**/*.{vue,ts,js}'

  stylelint:
    name: Check Stylelint Error
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: stylelint review
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          packages: 'stylelint-prettier stylelint-scss stylelint-order'
          stylelint_config: ./stylelint.config.js
          stylelint_input: '**/*.{css,scss,vue}'
