# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: reviewdog

on:
  pull_request:
    types: [opened, synchronize]


defaults:
  run:
    working-directory: ./test

jobs:
  eslint:
    name: Check Eslint Error
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Review eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: '**/*.{vue,ts,js}'
          workDir: ./test
      - name: Install packages
        run: npm ci
      - name: Check Eslint
        run: npm run lint

  stylelint:
    name: Check Stylelint Error
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: stylelint review
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          stylelint_input: '**/*.{css,scss,vue}'
          workDir: ./test
      - name: Install packages
        run: npm ci
      - name: Check Stylelint
        run: npm run lint:style
