# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint

on:
  pull_request:
    types: [opened, synchronize]


defaults:
  run:
    working-directory: ./test

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: reviewdog eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: '**/*.{vue,ts,js}'
          workdir: ./test
          reporter: github-pr-review
          fail_on_error: true

  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: reviewdog stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workDir: ./test
          stylelint_input: '**/*.{css,scss,vue}'
          packages: 'stylelint-prettier stylelint-scss stylelint-order'
          reporter: github-pr-review
          fail_on_error: true
